package io.fourfinanceit.setup

import groovy.transform.CompileStatic
import groovy.transform.ToString
import org.gradle.api.Project
import org.yaml.snakeyaml.Yaml

@ToString(ignoreNulls = true)
@CompileStatic
class Options {

    final Maven maven
    final Custom custom
    final Accurest accurest
    final MicroInfra microInfra

    Options(Maven maven, Custom custom, Accurest accurest, MicroInfra microInfra) {
        this.maven = maven
        this.custom = custom
        this.accurest = accurest
        this.microInfra = microInfra
    }

    void process(Project project) {
        Properties gradleProps = loadGradleProperties(project)
        Map appPropsEntries = [:]
        maven.process(gradleProps)
        accurest.process(gradleProps)
        microInfra.process(appPropsEntries)
        custom.process(accurest)
        gradleProps.store(getGradleProps(project).newWriter(), "Autogenerated properties via ./gradlew setup - clean it as you wish ;)")
        storeApplicationConfiguration(project, appPropsEntries)
    }

    private Properties loadGradleProperties(Project project) {
        File gradleProps = getGradleProps(project)
        Properties props = new Properties()
        props.load(gradleProps.newReader())
        return props
    }

    private File getGradleProps(Project project) {
        return project.file('gradle.properties')
    }

    private void storeApplicationConfiguration(Project project, Map appPropsEntries) {
        File appProps = project.file('src/main/resources/application.yaml')
        appProps.createNewFile()
        new Yaml().dump(appPropsEntries, appProps.newWriter())
    }

}
