city.finding.service.url: "http://api.openweathermap.org/data/2.5/weather"

metrics.path:
  country: pl
  app: service-name

request.payload.logging.maxlength: 2000

server.port: 8099

spring:
  datasource:
    username: twitter-places-analyzer

  jackson.deserialization.fail-on-unknown-properties: false
  groovy.template.check-template-location: false

stubrunner:
  use-microservice-definitions: true
  stubs:
    repository.root: "http://dl.bintray.com/4finance/micro"
    group: com.ofg
    module: stub-runner-examples
